version: "3.9"

services:
  users-service:
    build: ./users-service
    container_name: users-service
    networks:
      - desafio5-net

  orders-service:
    build: ./orders-service
    container_name: orders-service
    networks:
      - desafio5-net

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8000:8000"
    depends_on:
      - users-service
      - orders-service
    networks:
      - desafio5-net

networks:
  desafio5-net:
    driver: bridge
